### PR TITLE
fix: split deployment job and give it write permission

### PR DESCRIPTION
**Pull request by Saransh-cpp**
The new deployment workflow did not work as expected - https://github.com/UCL/rsd-engineeringcourse/actions/runs/10389062533 💀 

This PR fixes it. Passing workflow on my fork - https://github.com/Saransh-cpp/rsd-engineeringcourse/actions/runs/10389554321. Deployed website on my fork - https://saransh-cpp.github.io/rsd-engineeringcourse/.

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
I have updated the pages to use GH Actions instead of the `gh-pages` branch in settings. I will also update the "required" workflows/status checks once this PR is merged.

**Review by dpshelio — APPROVED** [review]
:building_construction: :rocket:

**Comment by dpshelio** [comment]
I can't merge it... I wonder if it's because deploy is not happening on this PR and gh is awaiting for it.

**Comment by Saransh-cpp** [comment]
Oops, forgot updating the "required checks" setting 😞 

Should work now!

**Pull request merged**
