### PR TITLE
New exercise 1

### PR DESCRIPTION
**Pull request by jamespjh**
@sgrieve @MattClarkson what do you think of this for a new exercise, which it should be possible to write a semi-automated marking tool for?

### CODE REVIEW

**Comment by sgrieve** [comment]
@jamespjh I really like this. I've gone through it all and didn't find any typos/obvious things that need corrected. I'm confident that I have covered the material they will need to draw on in order to complete this assignment, and don't see any major roadblocks for the students in the assignment.

One thought I had, should we require PEP8 compliant code? If we do, we can assign the marks for code tidiness/formatting uniformly and without any personal bias. I spoke about PEP8 and code formatting in lecture 2, so it shouldn't be a totally new concept, and it inches us towards CI...

**Comment by MattClarkson** [comment]
will check tonight.

**Comment by MattClarkson** [comment]
Looks good. Comments.

* "and demonstrate your ability to use git version control."
* Can we specify that the solution should not be placed on a public git repo, as we will install it from the submitted repo.
* While there is a mandate to have very prescriptive marking schemes, I'd prefer to have marks out of 100, as you end up with very coarse steps, in multiples of 4. However, last year we then have problems of consistently applying a set of rules. Im not sure I have a better solution in mind.
* Looking at the mark scheme, and bearing in mind the difference last year between a good report and a bad report, then "reflections on project" and "consideration of problems" need to be more specific, or removed. Otherwise, a good student could write a full page, and a poor student could write one line, and both technically score the same marks.

**Comment by jamespjh** [comment]
I have made changes per code review by @MattClarkson and @sgrieve . @MattClarkson are we OK to distribute?

**Comment by MattClarkson** [comment]
Yes, ok to distribute.

**Comment by MattClarkson** [comment]
(and thanks of course)

**Pull request merged**
