### PR TITLE
cython draft

### PR DESCRIPTION
**Pull request by jamespjh**

### CODE REVIEW

**Comment by sinanshi** [comment]
cython course material updated. @jamespjh can you review it?

**Comment by jamespjh** [comment]
"with comparable performance of" -> "with comparable performance to that of"

**Comment by jamespjh** [comment]
"medelbrot" -> "mandelbrot"

**Comment by jamespjh** [comment]
Sections like

```
%timeit a=mandel(complex(0,0)) # pure python
%timeit a=mandel_cython(complex(0,0)) # premitive cython
%timeit a=var_typed_mandel_cython(complex(0,0)) # cython with C type variable
%timeit a=call_typed_mandel_cython(complex(0,0)) # cython with typed variable + function
```

would be easier to understand as four separate cells each with its own result

**Pull request merged**
